# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slack_nickname', models.CharField(max_length=128)),
                ('flag_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
