# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_rotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='deleted_at',
            new_name='canceled_date',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='made_date',
            new_name='choosed_date',
        ),
    ]
