# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_rotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='removed_by',
            field=models.ForeignKey(db_column='removed_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_REMOVED_BY', to=settings.AUTH_USER_MODEL),
        ),
    ]
